Name:           ros-lunar-explore-lite
Version:        2.1.1
Release:        0%{?dist}
Summary:        ROS explore_lite package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/explore_lite
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-actionlib
Requires:       ros-lunar-actionlib-msgs
Requires:       ros-lunar-costmap-2d
Requires:       ros-lunar-geometry-msgs
Requires:       ros-lunar-map-msgs
Requires:       ros-lunar-move-base-msgs
Requires:       ros-lunar-nav-msgs
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-std-msgs
Requires:       ros-lunar-tf
Requires:       ros-lunar-visualization-msgs
BuildRequires:  ros-lunar-actionlib
BuildRequires:  ros-lunar-actionlib-msgs
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-costmap-2d
BuildRequires:  ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-map-msgs
BuildRequires:  ros-lunar-move-base-msgs
BuildRequires:  ros-lunar-nav-msgs
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-roslaunch
BuildRequires:  ros-lunar-std-msgs
BuildRequires:  ros-lunar-tf
BuildRequires:  ros-lunar-visualization-msgs

%description
Lightweight frontier-based exploration.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Sat Dec 16 2017 Jiri Horner <laeqten@gmail.com> - 2.1.1-0
- Autogenerated by Bloom

* Mon Oct 30 2017 Jiri Horner <laeqten@gmail.com> - 2.1.0-0
- Autogenerated by Bloom

